import request from '@/utils/request'

export function getQcCastReelList(params) {
  return request({
    url: '/lmdpQcCastReel/list',
    method: 'get',
    params
  })
}
export const formJson4= {
  "widgetList": [
    {
      "type": "alert",
      "icon": "alert",
      "formItemFlag": false,
      "options": {
        "name": "alert41369",
        "title": "铸轧卷质检报告单",
        "type": "success",
        "description": "",
        "closable": false,
        "closeText": "",
        "center": true,
        "showIcon": false,
        "effect": "light",
        "hidden": false,
        "onClose": "",
        "customClass": [],
        "label": "alert"
      },
      "id": "alert41369"
    },
    {
      "type": "grid",
      "category": "container",
      "icon": "grid",
      "cols": [
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "reelNum",
                "label": "批号",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": null,
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input67808"
            }
          ],
          "options": {
            "name": "gridCol82012",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-82012"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "model",
                "label": "规格",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": null,
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input32801"
            }
          ],
          "options": {
            "name": "gridCol50816",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-50816"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "brand",
                "label": "牌号",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": null,
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input24483"
            }
          ],
          "options": {
            "name": "gridCol75246",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-75246"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "weight",
                "label": "重量",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": null,
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input45346"
            }
          ],
          "options": {
            "name": "gridCol67425",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-67425"
        }
      ],
      "options": {
        "name": "grid15267",
        "hidden": false,
        "gutter": 12,
        "colHeight": null,
        "customClass": ""
      },
      "id": "grid15267"
    },
    {
      "type": "grid",
      "category": "container",
      "icon": "grid",
      "cols": [
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "wt",
                "label": "化学成份",
                "labelAlign": "label-right-align",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "optionItems": [
                  {
                    "value": "qualified",
                    "label": "合格"
                  },
                  {
                    "value": "review",
                    "label": "发评审"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select42435"
            }
          ],
          "options": {
            "name": "gridCol84942",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-84942"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "wtRemark",
                "label": "化学成分备注",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input45364"
            }
          ],
          "options": {
            "name": "gridCol44394",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-44394"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "hdaf",
                "label": "铝熔体氢含量",
                "labelAlign": "label-right-align",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "optionItems": [
                  {
                    "value": "qualified",
                    "label": "合格"
                  },
                  {
                    "value": "review",
                    "label": "发评审"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select52217"
            }
          ],
          "options": {
            "name": "gridCol47703",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-47703"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "hdafRemark",
                "label": "铝熔体氢含量备注",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input24980"
            }
          ],
          "options": {
            "name": "gridCol90100",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-90100"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "lpsSize",
                "label": "低倍组织",
                "labelAlign": "label-right-align",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "optionItems": [
                  {
                    "value": "qualified",
                    "label": "合格"
                  },
                  {
                    "value": "review",
                    "label": "发评审"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select84352"
            }
          ],
          "options": {
            "name": "gridCol28467",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-28467"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "lpsPicture",
                "label": "低倍组织图片",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input49773"
            }
          ],
          "options": {
            "name": "gridCol77214",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-77214"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "lpsSizeRemark",
                "label": "低倍组织备注",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input48693"
            }
          ],
          "options": {
            "name": "gridCol27636",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-27636"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "hpsSize",
                "label": "高倍组织",
                "labelAlign": "label-right-align",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "optionItems": [
                  {
                    "value": "qualified",
                    "label": "合格"
                  },
                  {
                    "value": "review",
                    "label": "发评审"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select96523"
            }
          ],
          "options": {
            "name": "gridCol64410",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-64410"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "hpsPicture",
                "label": "高倍组织图片",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input103825"
            }
          ],
          "options": {
            "name": "gridCol30382",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-30382"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "hpsSizeRemark",
                "label": "高倍组织备注",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input6430"
            }
          ],
          "options": {
            "name": "gridCol85493",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-85493"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "sampleLevel",
                "label": "晶粒度",
                "labelAlign": "label-right-align",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "optionItems": [
                  {
                    "value": "1",
                    "label": "1级"
                  },
                  {
                    "value": "2",
                    "label": "2级"
                  },
                  {
                    "value": "3",
                    "label": "3级"
                  },
                  {
                    "value": "4",
                    "label": "4级"
                  },
                  {
                    "value": "5",
                    "label": "5级"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select63879"
            }
          ],
          "options": {
            "name": "gridCol26872",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-26872"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "sampleLevelPicture",
                "label": "晶粒度图片",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input80384"
            }
          ],
          "options": {
            "name": "gridCol64961",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-64961"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "shapeQc",
                "label": "板型质量",
                "labelAlign": "label-right-align",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "optionItems": [
                  {
                    "value": "qualified",
                    "label": "合格"
                  },
                  {
                    "value": "review",
                    "label": "发评审"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select67577"
            }
          ],
          "options": {
            "name": "gridCol70358",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-70358"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "shapeQcRemark",
                "label": "板型质量备注",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input114974"
            }
          ],
          "options": {
            "name": "gridCol59272",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-59272"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "dimensionalDeviation",
                "label": "尺寸偏差",
                "labelAlign": "label-right-align",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": null,
                "labelHidden": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "optionItems": [
                  {
                    "value": "qualified",
                    "label": "合格"
                  },
                  {
                    "value": "review",
                    "label": "发评审"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select70276"
            }
          ],
          "options": {
            "name": "gridCol87759",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-87759"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "thickness",
                "label": "厚度(mm)",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": null,
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input20897"
            }
          ],
          "options": {
            "name": "gridCol50995",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-50995"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "width",
                "label": "宽度(mm)",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": null,
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input18056"
            }
          ],
          "options": {
            "name": "gridCol55845",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-55845"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "dimensionalDeviationRemark",
                "label": "尺寸偏差备注",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "100",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input82689"
            }
          ],
          "options": {
            "name": "gridCol90207",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-90207"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "facadeQc",
                "label": "外观质量",
                "labelAlign": "label-right-align",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": null,
                "labelHidden": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "optionItems": [
                  {
                    "value": "qualified",
                    "label": "合格"
                  },
                  {
                    "value": "review",
                    "label": "发评审"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select81524"
            }
          ],
          "options": {
            "name": "gridCol55651",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-55651"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "facadeQcRemark",
                "label": "外观质量备注",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "100",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input16804"
            }
          ],
          "options": {
            "name": "gridCol54662",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-54662"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "surfaceQc",
                "label": "表面质量",
                "labelAlign": "label-right-align",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": null,
                "labelHidden": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "optionItems": [
                  {
                    "value": "qualified",
                    "label": "合格"
                  },
                  {
                    "value": "review",
                    "label": "发评审"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select51804"
            }
          ],
          "options": {
            "name": "gridCol91367",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-91367"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "surfaceQcRemark",
                "label": "表面质量备注",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "100",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input96156"
            }
          ],
          "options": {
            "name": "gridCol103551",
            "hidden": false,
            "span": 12,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-103551"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "judgeReamrk",
                "label": "质量缺陷描述",
                "labelAlign": "",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "100",
                "labelHidden": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "optionItems": [
                  {
                    "value": "LBonly",
                    "label": "裂边"
                  },
                  {
                    "value": "LBGC",
                    "label": "裂边、贯穿"
                  },
                  {
                    "value": "ZXPX",
                    "label": "中心偏析"
                  },
                  {
                    "value": "CJT",
                    "label": "粗晶条"
                  },
                  {
                    "value": "BMPX",
                    "label": "表面偏析"
                  },
                  {
                    "value": "CFXBFe",
                    "label": "成分超标Fe"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select87220"
            }
          ],
          "options": {
            "name": "gridCol95287",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-95287"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "judgeResult",
                "label": "质量判定结果",
                "labelAlign": "",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "100",
                "labelHidden": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "optionItems": [
                  {
                    "value": "reform",
                    "label": "改制"
                  },
                  {
                    "value": "scrap",
                    "label": "报废"
                  },
                  {
                    "value": "release",
                    "label": "合格B(让步放行)"
                  },
                  {
                    "value": "qualifieda",
                    "label": "合格A"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select18896"
            }
          ],
          "options": {
            "name": "gridCol114741",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-114741"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "reviewAdvice",
                "label": "发评审建议",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "100",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input66156"
            }
          ],
          "options": {
            "name": "gridCol100716",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-100716"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "creatorId",
                "label": "质检员",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "100",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input82007"
            }
          ],
          "options": {
            "name": "gridCol68936",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-68936"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "auditor",
                "label": "审核员",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "100",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input60756"
            }
          ],
          "options": {
            "name": "gridCol71889",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-71889"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "inspectMonitorCheck",
                "label": "质检班长复核",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "100",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input60788"
            }
          ],
          "options": {
            "name": "gridCol35776",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-35776"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "reportTime",
                "label": "日期及时间",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "100",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input46560"
            }
          ],
          "options": {
            "name": "gridCol24271",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-24271"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "advise",
                "label": "处理意见",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "100",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input88776"
            }
          ],
          "options": {
            "name": "gridCol90544",
            "hidden": false,
            "span": 6,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-90544"
        }
      ],
      "options": {
        "name": "grid75362",
        "hidden": false,
        "gutter": 12,
        "colHeight": null,
        "customClass": ""
      },
      "id": "grid75362"
    }
  ],
  "formConfig": {
    "modelName": "formData",
    "refName": "vForm",
    "rulesName": "rules",
    "labelWidth": 80,
    "labelPosition": "left",
    "size": "",
    "labelAlign": "label-left-align",
    "cssCode": "\n.text-color{\n  color: black;\n}\n.text-size{\n  font-size: 15px;\n}\n\n.text-weizhi{\n  text-align: center;\n}",
    "customClass": "",
    "functions": "",
    "layoutType": "PC",
    "onFormCreated": "",
    "onFormMounted": "",
    "onFormDataChange": "",
    "jsonVersion": 2,
    "dataSources": [],
    "onFormValidate": ""
  }
}