import request from '@/utils/request'

export function getColdFurnaceRecordList(params) {
  return request({
    url: '/lmdpCastHoldingFurnace/list',
    method: 'get',
    params
  })
}8
export const formJson8= {
  "widgetList": [
    {
      "type": "alert",
      "icon": "alert",
      "formItemFlag": false,
      "options": {
        "name": "alert29910",
        "title": "轧卷信息",
        "type": "success",
        "description": "",
        "closable": false,
        "closeText": "",
        "center": true,
        "showIcon": false,
        "effect": "light",
        "hidden": false,
        "onClose": "",
        "customClass": "",
        "label": "alert"
      },
      "id": "alert29910"
    },
    {
      "type": "table",
      "category": "container",
      "icon": "table",
      "rows": [
        {
          "cols": [
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "static-text",
                  "icon": "static-text",
                  "formItemFlag": false,
                  "options": {
                    "name": "statictext38249",
                    "columnWidth": "200px",
                    "hidden": false,
                    "textContent": "装炉炉号",
                    "textAlign": "center",
                    "fontSize": "",
                    "preWrap": false,
                    "customClass": [
                      "text-size",
                      "text-color",
                      "text-weizhi"
                    ],
                    "onCreated": "",
                    "onMounted": "",
                    "label": "static-text"
                  },
                  "id": "statictext38249"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-68657",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-68657"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "select",
                  "icon": "select-field",
                  "formItemFlag": true,
                  "options": {
                    "name": "furnaceNum",
                    "label": "",
                    "labelAlign": "label-right-align",
                    "defaultValue": "",
                    "placeholder": "",
                    "columnWidth": "200px",
                    "size": "",
                    "labelWidth": "0",
                    "labelHidden": false,
                    "labelWrap": false,
                    "disabled": true,
                    "hidden": false,
                    "clearable": false,
                    "filterable": false,
                    "allowCreate": false,
                    "remote": false,
                    "automaticDropdown": false,
                    "multiple": false,
                    "multipleLimit": 0,
                    "dsEnabled": false,
                    "dsName": "",
                    "dataSetName": "",
                    "labelKey": "label",
                    "valueKey": "value",
                    "optionItems": [
                      {
                        "value": "1",
                        "label": "1"
                      },
                      {
                        "value": "2",
                        "label": "2"
                      },
                      {
                        "value": "3",
                        "label": "3"
                      },
                      {
                        "value": "4",
                        "label": "4"
                      },
                      {
                        "value": "5",
                        "label": "5"
                      }
                    ],
                    "required": false,
                    "requiredHint": "",
                    "validation": "",
                    "validationHint": "",
                    "customClass": [],
                    "labelIconClass": null,
                    "labelIconPosition": "rear",
                    "labelTooltip": null,
                    "onCreated": "",
                    "onMounted": "",
                    "onRemoteQuery": "",
                    "onChange": "",
                    "onFocus": "",
                    "onBlur": "",
                    "onValidate": ""
                  },
                  "id": "select82067"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-109953",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-109953"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [],
              "merged": false,
              "options": {
                "name": "table-cell-69479",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-69479"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [],
              "merged": false,
              "options": {
                "name": "table-cell-68111",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-68111"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [],
              "merged": false,
              "options": {
                "name": "table-cell-44141",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-44141"
            }
          ],
          "id": "table-row-47053",
          "merged": false
        },
        {
          "cols": [
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "static-text",
                  "icon": "static-text",
                  "formItemFlag": false,
                  "options": {
                    "name": "statictext48987",
                    "columnWidth": "200px",
                    "hidden": false,
                    "textContent": "装炉位置",
                    "textAlign": "center",
                    "fontSize": "",
                    "preWrap": false,
                    "customClass": [
                      "text-color",
                      "text-size",
                      "text-weizhi"
                    ],
                    "onCreated": "",
                    "onMounted": "",
                    "label": "static-text"
                  },
                  "id": "statictext48987"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-83064",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-83064"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "input",
                  "icon": "text-field",
                  "formItemFlag": true,
                  "options": {
                    "name": "furnacePosition",
                    "label": "",
                    "labelAlign": "label-center-align",
                    "type": "text",
                    "defaultValue": "",
                    "placeholder": "",
                    "columnWidth": "200px",
                    "size": "",
                    "labelWidth": "0",
                    "labelHidden": false,
                    "readonly": true,
                    "disabled": false,
                    "hidden": false,
                    "clearable": false,
                    "showPassword": false,
                    "required": false,
                    "requiredHint": "",
                    "validation": "",
                    "validationHint": "",
                    "customClass": "",
                    "labelIconClass": null,
                    "labelIconPosition": "rear",
                    "labelTooltip": null,
                    "minLength": null,
                    "maxLength": null,
                    "showWordLimit": false,
                    "prefixIcon": "",
                    "suffixIcon": "",
                    "appendButton": false,
                    "appendButtonDisabled": false,
                    "buttonIcon": "el-icon-search",
                    "onCreated": "",
                    "onMounted": "",
                    "onInput": "",
                    "onChange": "",
                    "onFocus": "",
                    "onBlur": "",
                    "onValidate": ""
                  },
                  "id": "input69829"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-81084",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": []
              },
              "id": "table-cell-81084"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "input",
                  "icon": "text-field",
                  "formItemFlag": true,
                  "options": {
                    "name": "furnacePosition2",
                    "label": "",
                    "labelAlign": "label-center-align",
                    "type": "text",
                    "defaultValue": "",
                    "placeholder": "",
                    "columnWidth": "200px",
                    "size": "",
                    "labelWidth": "0",
                    "labelHidden": false,
                    "readonly": true,
                    "disabled": false,
                    "hidden": false,
                    "clearable": false,
                    "showPassword": false,
                    "required": false,
                    "requiredHint": "",
                    "validation": "",
                    "validationHint": "",
                    "customClass": "",
                    "labelIconClass": null,
                    "labelIconPosition": "rear",
                    "labelTooltip": null,
                    "minLength": null,
                    "maxLength": null,
                    "showWordLimit": false,
                    "prefixIcon": "",
                    "suffixIcon": "",
                    "appendButton": false,
                    "appendButtonDisabled": false,
                    "buttonIcon": "el-icon-search",
                    "onCreated": "",
                    "onMounted": "",
                    "onInput": "",
                    "onChange": "",
                    "onFocus": "",
                    "onBlur": "",
                    "onValidate": ""
                  },
                  "id": "input80655"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-42860",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-42860"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "input",
                  "icon": "text-field",
                  "formItemFlag": true,
                  "options": {
                    "name": "furnacePosition3",
                    "label": "",
                    "labelAlign": "label-center-align",
                    "type": "text",
                    "defaultValue": "",
                    "placeholder": "",
                    "columnWidth": "200px",
                    "size": "",
                    "labelWidth": "0",
                    "labelHidden": false,
                    "readonly": true,
                    "disabled": false,
                    "hidden": false,
                    "clearable": false,
                    "showPassword": false,
                    "required": false,
                    "requiredHint": "",
                    "validation": "",
                    "validationHint": "",
                    "customClass": "",
                    "labelIconClass": null,
                    "labelIconPosition": "rear",
                    "labelTooltip": null,
                    "minLength": null,
                    "maxLength": null,
                    "showWordLimit": false,
                    "prefixIcon": "",
                    "suffixIcon": "",
                    "appendButton": false,
                    "appendButtonDisabled": false,
                    "buttonIcon": "el-icon-search",
                    "onCreated": "",
                    "onMounted": "",
                    "onInput": "",
                    "onChange": "",
                    "onFocus": "",
                    "onBlur": "",
                    "onValidate": ""
                  },
                  "id": "input110480"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-13421",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-13421"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "input",
                  "icon": "text-field",
                  "formItemFlag": true,
                  "options": {
                    "name": "furnacePosition4",
                    "label": "",
                    "labelAlign": "label-center-align",
                    "type": "text",
                    "defaultValue": "",
                    "placeholder": "",
                    "columnWidth": "200px",
                    "size": "",
                    "labelWidth": "0",
                    "labelHidden": false,
                    "readonly": true,
                    "disabled": false,
                    "hidden": false,
                    "clearable": false,
                    "showPassword": false,
                    "required": false,
                    "requiredHint": "",
                    "validation": "",
                    "validationHint": "",
                    "customClass": "",
                    "labelIconClass": null,
                    "labelIconPosition": "rear",
                    "labelTooltip": null,
                    "minLength": null,
                    "maxLength": null,
                    "showWordLimit": false,
                    "prefixIcon": "",
                    "suffixIcon": "",
                    "appendButton": false,
                    "appendButtonDisabled": false,
                    "buttonIcon": "el-icon-search",
                    "onCreated": "",
                    "onMounted": "",
                    "onInput": "",
                    "onChange": "",
                    "onFocus": "",
                    "onBlur": "",
                    "onValidate": ""
                  },
                  "id": "input84863"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-26766",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-26766"
            }
          ],
          "id": "table-row-45930",
          "merged": false
        },
        {
          "cols": [
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "static-text",
                  "icon": "static-text",
                  "formItemFlag": false,
                  "options": {
                    "name": "statictext119089",
                    "columnWidth": "200px",
                    "hidden": false,
                    "textContent": "冷轧卷号",
                    "textAlign": "center",
                    "fontSize": "",
                    "preWrap": false,
                    "customClass": [
                      "text-color",
                      "text-size",
                      "text-weizhi"
                    ],
                    "onCreated": "",
                    "onMounted": "",
                    "label": "static-text"
                  },
                  "id": "statictext119089"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-32903",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-32903"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "input",
                  "icon": "text-field",
                  "formItemFlag": true,
                  "options": {
                    "name": "batchNum",
                    "label": "",
                    "labelAlign": "label-center-align",
                    "type": "text",
                    "defaultValue": "",
                    "placeholder": "",
                    "columnWidth": "200px",
                    "size": "",
                    "labelWidth": "0",
                    "labelHidden": false,
                    "readonly": true,
                    "disabled": false,
                    "hidden": false,
                    "clearable": false,
                    "showPassword": false,
                    "required": false,
                    "requiredHint": "",
                    "validation": "",
                    "validationHint": "",
                    "customClass": "",
                    "labelIconClass": null,
                    "labelIconPosition": "rear",
                    "labelTooltip": null,
                    "minLength": null,
                    "maxLength": null,
                    "showWordLimit": false,
                    "prefixIcon": "",
                    "suffixIcon": "",
                    "appendButton": false,
                    "appendButtonDisabled": false,
                    "buttonIcon": "el-icon-search",
                    "onCreated": "",
                    "onMounted": "",
                    "onInput": "",
                    "onChange": "",
                    "onFocus": "",
                    "onBlur": "",
                    "onValidate": ""
                  },
                  "id": "input72720"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-110454",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-110454"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "input",
                  "icon": "text-field",
                  "formItemFlag": true,
                  "options": {
                    "name": "batchNum2",
                    "label": "",
                    "labelAlign": "label-center-align",
                    "type": "text",
                    "defaultValue": "",
                    "placeholder": "",
                    "columnWidth": "200px",
                    "size": "",
                    "labelWidth": "0",
                    "labelHidden": false,
                    "readonly": true,
                    "disabled": false,
                    "hidden": false,
                    "clearable": false,
                    "showPassword": false,
                    "required": false,
                    "requiredHint": "",
                    "validation": "",
                    "validationHint": "",
                    "customClass": "",
                    "labelIconClass": null,
                    "labelIconPosition": "rear",
                    "labelTooltip": null,
                    "minLength": null,
                    "maxLength": null,
                    "showWordLimit": false,
                    "prefixIcon": "",
                    "suffixIcon": "",
                    "appendButton": false,
                    "appendButtonDisabled": false,
                    "buttonIcon": "el-icon-search",
                    "onCreated": "",
                    "onMounted": "",
                    "onInput": "",
                    "onChange": "",
                    "onFocus": "",
                    "onBlur": "",
                    "onValidate": ""
                  },
                  "id": "input84667"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-27363",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-27363"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "input",
                  "icon": "text-field",
                  "formItemFlag": true,
                  "options": {
                    "name": "batchNum3",
                    "label": "",
                    "labelAlign": "label-center-align",
                    "type": "text",
                    "defaultValue": "",
                    "placeholder": "",
                    "columnWidth": "200px",
                    "size": "",
                    "labelWidth": "0",
                    "labelHidden": false,
                    "readonly": true,
                    "disabled": false,
                    "hidden": false,
                    "clearable": false,
                    "showPassword": false,
                    "required": false,
                    "requiredHint": "",
                    "validation": "",
                    "validationHint": "",
                    "customClass": "",
                    "labelIconClass": null,
                    "labelIconPosition": "rear",
                    "labelTooltip": null,
                    "minLength": null,
                    "maxLength": null,
                    "showWordLimit": false,
                    "prefixIcon": "",
                    "suffixIcon": "",
                    "appendButton": false,
                    "appendButtonDisabled": false,
                    "buttonIcon": "el-icon-search",
                    "onCreated": "",
                    "onMounted": "",
                    "onInput": "",
                    "onChange": "",
                    "onFocus": "",
                    "onBlur": "",
                    "onValidate": ""
                  },
                  "id": "input23806"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-52085",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-52085"
            },
            {
              "type": "table-cell",
              "category": "container",
              "icon": "table-cell",
              "internal": true,
              "widgetList": [
                {
                  "type": "input",
                  "icon": "text-field",
                  "formItemFlag": true,
                  "options": {
                    "name": "batchNum4",
                    "label": "",
                    "labelAlign": "label-center-align",
                    "type": "text",
                    "defaultValue": "",
                    "placeholder": "",
                    "columnWidth": "200px",
                    "size": "",
                    "labelWidth": "0",
                    "labelHidden": false,
                    "readonly": true,
                    "disabled": false,
                    "hidden": false,
                    "clearable": false,
                    "showPassword": false,
                    "required": false,
                    "requiredHint": "",
                    "validation": "",
                    "validationHint": "",
                    "customClass": "",
                    "labelIconClass": null,
                    "labelIconPosition": "rear",
                    "labelTooltip": null,
                    "minLength": null,
                    "maxLength": null,
                    "showWordLimit": false,
                    "prefixIcon": "",
                    "suffixIcon": "",
                    "appendButton": false,
                    "appendButtonDisabled": false,
                    "buttonIcon": "el-icon-search",
                    "onCreated": "",
                    "onMounted": "",
                    "onInput": "",
                    "onChange": "",
                    "onFocus": "",
                    "onBlur": "",
                    "onValidate": ""
                  },
                  "id": "input56292"
                }
              ],
              "merged": false,
              "options": {
                "name": "table-cell-61519",
                "cellWidth": "",
                "cellHeight": "",
                "colspan": 1,
                "rowspan": 1,
                "wordBreak": false,
                "customClass": ""
              },
              "id": "table-cell-61519"
            }
          ],
          "id": "table-row-100967",
          "merged": false
        }
      ],
      "options": {
        "name": "table95700",
        "hidden": false,
        "customClass": ""
      },
      "id": "table95700"
    },
    {
      "type": "grid",
      "category": "container",
      "icon": "grid",
      "cols": [
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "furnaceCardNumber",
                "label": "数据标准",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": "",
                "onAppendButtonClick": ""
              },
              "id": "input108174"
            }
          ],
          "options": {
            "name": "gridCol36145",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-36145"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "brand",
                "label": "合金",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": "",
                "onAppendButtonClick": ""
              },
              "id": "input45500"
            }
          ],
          "options": {
            "name": "gridCol60905",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-60905"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "annealingThick",
                "label": "退火厚度",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": "",
                "onAppendButtonClick": ""
              },
              "id": "input95991"
            }
          ],
          "options": {
            "name": "gridCol80883",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-80883"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "rollNum",
                "label": "眷数(个)",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": "",
                "onAppendButtonClick": ""
              },
              "id": "input86979"
            }
          ],
          "options": {
            "name": "gridCol69579",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-69579"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "furnaceTotal",
                "label": "装炉总量",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": "",
                "onAppendButtonClick": ""
              },
              "id": "input19219"
            }
          ],
          "options": {
            "name": "gridCol5003",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-5003"
        }
      ],
      "options": {
        "name": "grid21159",
        "hidden": false,
        "gutter": 12,
        "colHeight": null,
        "customClass": ""
      },
      "id": "grid21159"
    },
    {
      "type": "alert",
      "icon": "alert",
      "formItemFlag": false,
      "options": {
        "name": "alert29455",
        "title": "退火信息",
        "type": "success",
        "description": "",
        "closable": false,
        "closeText": "",
        "center": true,
        "showIcon": false,
        "effect": "light",
        "hidden": false,
        "onClose": "",
        "customClass": "",
        "label": "alert"
      },
      "id": "alert29455"
    },
    {
      "type": "grid",
      "category": "container",
      "icon": "grid",
      "cols": [
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "date",
              "icon": "date-field",
              "formItemFlag": true,
              "options": {
                "name": "startTime",
                "label": "装炉时间",
                "labelAlign": "label-right-align",
                "type": "date",
                "defaultValue": null,
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "editable": false,
                "format": "yyyy-MM-dd HH:mm:ss",
                "valueFormat": "yyyy-MM-dd HH:mm:ss",
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "date84435"
            }
          ],
          "options": {
            "name": "gridCol88138",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-88138"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "date",
              "icon": "date-field",
              "formItemFlag": true,
              "options": {
                "name": "endTime",
                "label": "出炉时间",
                "labelAlign": "label-right-align",
                "type": "date",
                "defaultValue": null,
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "editable": false,
                "format": "yyyy-MM-dd HH:mm:ss",
                "valueFormat": "yyyy-MM-dd HH:mm:ss",
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "date112257"
            }
          ],
          "options": {
            "name": "gridCol75543",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-75543"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "totalTime",
                "label": "退火总用时",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": "",
                "onAppendButtonClick": ""
              },
              "id": "input52330"
            }
          ],
          "options": {
            "name": "gridCol25472",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-25472"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "furnaceOperator1Id",
                "label": "装炉人员",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": "",
                "onAppendButtonClick": ""
              },
              "id": "input92426"
            }
          ],
          "options": {
            "name": "gridCol123497",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-123497"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "furnaceOperator2Id",
                "label": "出炉人员",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input102041"
            }
          ],
          "options": {
            "name": "gridCol16825",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-16825"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "select",
              "icon": "select-field",
              "formItemFlag": true,
              "options": {
                "name": "tempPowerControl",
                "label": "料温控制",
                "labelAlign": "label-right-align",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "labelWrap": false,
                "disabled": true,
                "hidden": false,
                "clearable": false,
                "filterable": false,
                "allowCreate": false,
                "remote": false,
                "automaticDropdown": false,
                "multiple": false,
                "multipleLimit": 0,
                "dsEnabled": false,
                "dsName": "",
                "dataSetName": "",
                "labelKey": "label",
                "valueKey": "value",
                "optionItems": [
                  {
                    "value": "tempcontrol",
                    "label": "料温控制"
                  },
                  {
                    "value": "timecontrol",
                    "label": "时间控制"
                  }
                ],
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "onCreated": "",
                "onMounted": "",
                "onRemoteQuery": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "select39183"
            }
          ],
          "options": {
            "name": "gridCol33180",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-33180"
        }
      ],
      "options": {
        "name": "grid95178",
        "hidden": false,
        "gutter": 12,
        "colHeight": null,
        "customClass": []
      },
      "id": "grid95178"
    },
    {
      "type": "alert",
      "icon": "alert",
      "formItemFlag": false,
      "options": {
        "name": "alert72187",
        "title": "电耗量",
        "type": "success",
        "description": "",
        "closable": false,
        "closeText": "",
        "center": true,
        "showIcon": false,
        "effect": "light",
        "hidden": false,
        "onClose": "",
        "customClass": "",
        "label": "alert"
      },
      "id": "alert72187"
    },
    {
      "type": "grid",
      "category": "container",
      "icon": "grid",
      "cols": [
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "powerBefore",
                "label": "起始电量(kw.h)",
                "labelAlign": "",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": "",
                "onAppendButtonClick": ""
              },
              "id": "input34977"
            }
          ],
          "options": {
            "name": "gridCol102525",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-102525"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "powerAfter",
                "label": "终止电量(kw.h)",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input37719"
            }
          ],
          "options": {
            "name": "gridCol107478",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-107478"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "runningDuring",
                "label": "运行时长",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input102750"
            }
          ],
          "options": {
            "name": "gridCol56310",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-56310"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "powerLoss",
                "label": "本炉电耗(kw.h)",
                "labelAlign": "label-right-align",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": true,
                "disabled": false,
                "hidden": false,
                "clearable": false,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": ""
              },
              "id": "input49016"
            }
          ],
          "options": {
            "name": "gridCol31963",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-31963"
        },
        {
          "type": "grid-col",
          "category": "container",
          "icon": "grid-col",
          "internal": true,
          "widgetList": [
            {
              "type": "input",
              "icon": "text-field",
              "formItemFlag": true,
              "options": {
                "name": "perPowerLoss",
                "label": "吨电耗(kw.h/t)",
                "labelAlign": "",
                "type": "text",
                "defaultValue": "",
                "placeholder": "",
                "columnWidth": "200px",
                "size": "",
                "labelWidth": "120",
                "labelHidden": false,
                "readonly": false,
                "disabled": false,
                "hidden": false,
                "clearable": true,
                "showPassword": false,
                "required": false,
                "requiredHint": "",
                "validation": "",
                "validationHint": "",
                "customClass": "",
                "labelIconClass": null,
                "labelIconPosition": "rear",
                "labelTooltip": null,
                "minLength": null,
                "maxLength": null,
                "showWordLimit": false,
                "prefixIcon": "",
                "suffixIcon": "",
                "appendButton": false,
                "appendButtonDisabled": false,
                "buttonIcon": "el-icon-search",
                "onCreated": "",
                "onMounted": "",
                "onInput": "",
                "onChange": "",
                "onFocus": "",
                "onBlur": "",
                "onValidate": "",
                "onAppendButtonClick": ""
              },
              "id": "input113117"
            }
          ],
          "options": {
            "name": "gridCol79212",
            "hidden": false,
            "span": 8,
            "offset": 0,
            "push": 0,
            "pull": 0,
            "responsive": false,
            "md": 12,
            "sm": 12,
            "xs": 12,
            "customClass": ""
          },
          "id": "grid-col-79212"
        }
      ],
      "options": {
        "name": "grid24423",
        "hidden": false,
        "gutter": 12,
        "colHeight": null,
        "customClass": ""
      },
      "id": "grid24423"
    }
  ],
  "formConfig": {
    "modelName": "formData",
    "refName": "vForm",
    "rulesName": "rules",
    "labelWidth": 80,
    "labelPosition": "left",
    "size": "",
    "labelAlign": "label-left-align",
    "cssCode": ".text-color{\n  color: blue;\n}\n.text-color{\n  color: black;\n}\n.text-size{\n  font-size: 15px;\n}\n\n.text-weizhi{\n  text-align: center;\n}",
    "customClass": "",
    "functions": "",
    "layoutType": "PC",
    "onFormCreated": "",
    "onFormMounted": "",
    "onFormDataChange": "",
    "jsonVersion": 2,
    "dataSources": [],
    "onFormValidate": ""
  }
}
